### ISSUE TITLE
Can't get the playerSwitch or getRoundWinner functions to work

### ISSUE THREAD

**Issue by sclaney** [sclaney/Race_to_self_actualization#2]
Starting in line 57, I have my logic that tracks the keypresses to see if the response matches the prompt, and once it does the round is over and the user can click the button below so the next player can start the round. But for some reason, the playerSwitch function is only working one time to switch between player 1 to player 2 and not back after that. Also, it should run through the get winner logic for each round after player 2 is finished with a prompt, but it doesn't run.

**Comment by ghost** [comment]
Please resubmit with a user story, etc., according to the structure in the [issues protocol](https://github.com/ga-students/WDI_DTLA_4/tree/master/projects/project_issues_protocol). Closed #2.
